import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {dirname,join,extname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawn} from 'node:child_process';
const root=join(dirname(fileURLToPath(import.meta.url)),'..');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg','.mp4':'video/mp4'};
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://local').pathname;const file=join(root,path==='/'?'/index.html':path);res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream'});res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port+'/';
const chromePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
const profile=join(root,'.chrome-guides');await mkdir(profile,{recursive:true});await mkdir(join(root,'shots'),{recursive:true});
const browser=spawn(chromePath,['--headless=new','--remote-debugging-port=9876','--user-data-dir='+profile,'--no-first-run','--hide-scrollbars','--enable-unsafe-swiftshader','about:blank'],{stdio:'ignore'});
let ws;let failures=0;const errors=[];
const check=(v,label)=>{console.log((v?'  ok   ':'  FAIL ')+label);if(!v)failures++;};
try{
 let target;
 for(let i=0;i<80&&!target;i++){try{target=(await(await fetch('http://127.0.0.1:9876/json/list')).json()).find(x=>x.type==='page');}catch{}if(!target)await sleep(100);}
 ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
 let id=0;const pending=new Map();
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
 const send=(method,params={})=>new Promise(r=>{const n=++id;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async(expression)=>{const m=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description||m.result.exceptionDetails.text);return m.result.result.value;};
 const visit=async(path)=>{await send('Page.navigate',{url:path.startsWith('file:')?path:base+path});for(let i=0;i<70;i++){await sleep(100);if(await evaluate('!!window.__XM_GUIDE__ && [...document.styleSheets].some(s=>s.href?.endsWith("companion.css"))'))break;}await sleep(250);};
 const screenshot=async(name)=>{const m=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(root,'shots',name+'.png'),Buffer.from(m.result.data,'base64'));};
 const click=async(selector)=>{await evaluate('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"center"})');await sleep(250);const point=await evaluate('(()=>{const r=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()');await send('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1});await sleep(200);};
 await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 console.log('[同行者：选择、对话、跨页、手机、file://]');
 await visit('qiongnaieman/index.html');await evaluate('localStorage.removeItem("xiangmai.guide.v1");localStorage.removeItem("xiangmai.guide.auto.v1")');await visit('qiongnaieman/index.html');
 check(await evaluate('document.querySelectorAll(".guide-card").length===3 && document.getElementById("guide-dock").hidden'),'第二章有三个人物，未选择时不显示陪伴入口');
 await evaluate('document.getElementById("guide-selection").scrollIntoView({block:"center"})');await sleep(1400);
 check(await evaluate('[...document.querySelectorAll(".guide-card img")].every(i=>i.complete&&i.naturalWidth>0)'),'三张人物素材加载成功');
 check(await evaluate('document.querySelectorAll(".guide-card__stage.has-guide-actor canvas:not([hidden])").length===3'),'三个 2.5D 动作图集加载成功');
 await screenshot('guide-selection-desktop');
 await click('.guide-card[data-guide="miao"]');
 check(await evaluate('window.__XM_GUIDE__.state().selected==="miao" && !document.getElementById("guide-dock").hidden'),'实际点击卡片选中银铃');
 await sleep(900);
 check(await evaluate('window.__XM_GUIDE__.actor().loaded && window.__XM_GUIDE__.state().arrival'),'选择人物后开始三句介绍并加载动画');
 const firstLine=await evaluate('document.querySelector(".guide-hint p").textContent');
 await click('.guide-hint__next');
 check(await evaluate('window.__XM_GUIDE__.state().arrivalIndex===1 && document.querySelector(".guide-hint p").textContent!=='+JSON.stringify(firstLine)),'下一句切换介绍内容');
 await click('.guide-hint__next');
 check(await evaluate('window.__XM_GUIDE__.state().arrivalIndex===2'),'第三句章节介绍可继续阅读');
 await click('.guide-hint__next');
 check(await evaluate('!window.__XM_GUIDE__.state().arrival && document.querySelector(".guide-hint").hidden'),'介绍可完成并收起');
 await click('.guide-launcher');
 check(await evaluate('window.__XM_GUIDE__.state().open && document.querySelectorAll(".guide-dialog__topics button").length===3'),'点击人物打开三个本章话题');
 await click('.guide-dialog__topics button:last-child');
 check(await evaluate('document.querySelector(".guide-dialog__reply").textContent.includes("琴弓") && !document.querySelector(".guide-dialog__go").hidden'),'拉琴话题返回解释和体验入口');
 const talkFrames=await evaluate('new Promise(resolve=>{const frames=new Set();const timer=setInterval(()=>frames.add(window.__XM_GUIDE__.actor().frame),100);setTimeout(()=>{clearInterval(timer);resolve([...frames])},2100)})');
 check(talkFrames.includes(4)&&talkFrames.includes(5),'说话时切换两套表情与手势');
 await screenshot('guide-dialog-desktop');
 await click('.guide-dialog__go');await sleep(900);
 check(await evaluate('!window.__XM_GUIDE__.state().open && Math.abs(document.getElementById("bow-act").getBoundingClientRect().top)<innerHeight'),'对话可带用户到拉琴互动');
 await visit('dastan/index.html');
 check(await evaluate('window.__XM_GUIDE__.state().selected==="miao"'),'进入第三章保留银铃');
 await sleep(1800);
 check(await evaluate('window.__XM_GUIDE__.state().arrival && window.__XM_GUIDE__.state().arrivalIndex===0 && document.querySelector(".guide-hint p").textContent.includes("达斯坦")'),'切换章节自动开始本章三句介绍');
 await evaluate('window.__XM_GUIDE__.open(false)');
 check(await evaluate('!window.__XM_GUIDE__.state().arrival'),'用户打开聊天时停止章节介绍');
 check(await evaluate('document.querySelector(".guide-dialog__chapter").textContent.includes("达斯坦") && document.querySelector(".guide-dialog__topics").textContent.includes("间奏")'),'第三章话题随章节变化');
 await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
 check(await evaluate('!window.__XM_GUIDE__.state().open'),'Escape 收起对话');
 await visit('mashrap/index.html');
 await evaluate('document.getElementById("rlab-act").scrollIntoView({block:"center"})');await sleep(900);
 check(await evaluate('!document.querySelector(".guide-hint").hidden && document.querySelector(".guide-hint p").textContent.includes("敲")'),'浏览到节奏台主动提示');
 await evaluate('window.__XM_GUIDE__.open(false)');
 await click('.guide-auto');
 check(await evaluate('!window.__XM_GUIDE__.state().auto'),'可以关闭沿途提示');
 await visit('lishi/index.html');await sleep(1700);
 check(await evaluate('!window.__XM_GUIDE__.state().arrival && document.querySelector(".guide-hint").hidden'),'关闭沿途提示后不会自动介绍下一章');
 check(await evaluate('window.__XM_GUIDE__.state().selected==="miao" && !window.__XM_GUIDE__.state().auto'),'第五章保留人物和关闭提示的偏好');
 await evaluate('window.__XM_GUIDE__.open(false)');
 check(await evaluate('document.querySelector(".guide-dialog__chapter").textContent.includes("历史")'),'第五章有对应话题');
 await visit('fulu/index.html');await evaluate('window.__XM_GUIDE__.open(false)');
 check(await evaluate('document.querySelector(".guide-dialog__topics").textContent.includes("轮盘")'),'附录有对应话题');
 await visit('game/index.html?level=muqam');await evaluate('window.__XM_GUIDE__.open(false)');
 check(await evaluate('document.querySelector(".guide-dialog__topics").textContent.includes("这一关")'),'情境游戏也有自己的话题');
 await visit('heritage/index.html');await evaluate('window.__XM_GUIDE__.open(false)');
 check(await evaluate('document.querySelector(".guide-dialog__chapter").textContent.includes("八族")'),'八族总览有对应话题');
 await visit('heritage/miao-guge/index.html');await evaluate('window.__XM_GUIDE__.open(false)');
 check(await evaluate('document.querySelector(".guide-dialog__chapter").textContent.includes("苗族") && document.querySelector(".guide-launcher img").complete && document.querySelector(".guide-launcher img").naturalWidth>0'),'嵌套民族档案正确显示人物和本页话题');
 await click('.guide-dialog__switch');await click('.guide-dialog__topics button:last-child');
 check(await evaluate('window.__XM_GUIDE__.state().selected==="mongol"'),'可在后续章节换成青岚');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await visit('qiongnaieman/index.html');
 await evaluate('window.__XM_GUIDE__.close(false);document.getElementById("guide-selection").scrollIntoView({block:"start"})');await sleep(600);await screenshot('guide-selection-mobile');
 await evaluate('window.__XM_GUIDE__.open(false)');await sleep(200);
 check(await evaluate('(()=>{const r=document.querySelector(".guide-dialog").getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth && r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight})()'),'390px 手机对话面板完整可见且无横向溢出');
 await screenshot('guide-dialog-mobile');
 await send('Emulation.setDeviceMetricsOverride',{width:320,height:640,deviceScaleFactor:1,mobile:true});
 check(await evaluate('(()=>{const r=document.querySelector(".guide-dialog").getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight})()'),'320px 窄屏对话可用');
 await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await visit('qiongnaieman/index.html');
 await sleep(1000);
 check(await evaluate('window.__XM_GUIDE__.actor().loaded && !window.__XM_GUIDE__.actor().animated && window.__XM_GUIDE__.actor().frame===0'),'尊重减弱动效设置');
 await send('Emulation.setEmulatedMedia',{features:[]});
 await visit('qiongnaieman/index.html');await sleep(900);await evaluate('window.__XM_GUIDE__.close(false)');
 const idleFrames=await evaluate('new Promise(resolve=>{const frames=new Set();const timer=setInterval(()=>frames.add(window.__XM_GUIDE__.actor().frame),60);setTimeout(()=>{clearInterval(timer);resolve([...frames])},13500)})');
 check([0,1,2,3].every(f=>idleFrames.includes(f)),'待机包含静立、眨眼、偏头和招手四种姿态');
 await visit(pathToFileURL(join(root,'qiongnaieman/index.html')).href);
 await evaluate('window.__XM_GUIDE__.choose("uyghur");window.__XM_GUIDE__.open(false)');await sleep(1000);
 check(await evaluate('window.__XM_GUIDE__.state().selected==="uyghur" && document.querySelector(".guide-launcher img").naturalWidth>0'),'file:// 直接打开也能选择、对话和加载人物');
 await visit(pathToFileURL(join(root,'dastan/index.html')).href);
 check(await evaluate('window.__XM_GUIDE__.state().selected==="uyghur"'),'本机 Chrome 中 file:// 跨页保留选择');
 const inject=await send('Page.addScriptToEvaluateOnNewDocument',{source:'Object.defineProperty(Storage.prototype,"getItem",{value(){throw Error("storage disabled")}});Object.defineProperty(Storage.prototype,"setItem",{value(){throw Error("storage disabled")}});'});
 await visit('qiongnaieman/index.html');await evaluate('window.__XM_GUIDE__.choose("miao");window.__XM_GUIDE__.open(false)');
 check(await evaluate('window.__XM_GUIDE__.state().selected==="miao" && window.__XM_GUIDE__.state().open'),'存储被禁用时本页选择和对话仍可用');
 await send('Page.removeScriptToEvaluateOnNewDocument',{identifier:inject.result.identifier});
 check(!errors.length,'无 JavaScript 运行时异常'+(errors.length?': '+errors.join('\n'):''));
}catch(e){check(false,e.stack||e.message);}finally{ws?.close();browser.kill();server.close();}
console.log(failures?'✗ '+failures+' 项失败':'✓ 同行者检查全部通过');process.exit(failures?1:0);
